# Практика №2
## Робота з NumPy


In [2]:
import numpy as np

1. Створіть вектор (1,2,3) і виведіть його. Виведіть тип масиву.
2. Створіть наступну матрицю і виведіть її:
$$
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right)
$$ 
3. Створіть нульову матрицю розміром (4,5) - див. numpy.zeros.
4. Створіть одиничну матрицю розміром (3,3) - див. numpy.identity.
5. Виведіть розмір матриці, створеної на 2 кроці.
6. Створити дві матриці  $A = 
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6
\end{array}\right)
$ і $B = 
\left(\begin{array}{cc} 
-1 & -2 & -3\\
-4 & -5 & -6
\end{array}\right)
$. Виконайте операції додавання і віднімання для цих двох матриць.
7. Для вищезазначених матриць виконайте поелементне множення.
8. До матриці $A$ додайте константу $b=2$.
9. Виконайте множення матриці $\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6
\end{array}\right)
$ на матрицю $\left(\begin{array}{cc} 
1 & 1\\
1 & 1\\
1 & 1
\end{array}\right)
$
10. Для двох векторів $v = (1,2,3)$ і $u = (1,1,1)$ знайти Евклідову норму (див. numpy.linalg.norm)
11. Дано вектор $[11,22,33,44,55]$. Необхідно вивести усі елементи від передостаннього елемента до кінця (використайте зріз).


In [4]:
vector = np.array([1, 2, 3])
print("Vector:", vector)
print("Type:", type(vector))

Vector: [1 2 3]
Type: <class 'numpy.ndarray'>


In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatrix:\n", matrix)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
zero_matrix = np.zeros((4, 5))
print("\nZero Matrix:\n", zero_matrix)


Zero Matrix:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
identity_matrix = np.identity(3)
print("\nIdentity Matrix:\n", identity_matrix)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
matrix_size = matrix.shape
print("\nMatrix Size:", matrix_size)


Matrix Size: (3, 3)


In [10]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-1, -2, -3], [-4, -5, -6]])

addition_result = A + B
subtraction_result = A - B

print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nAddition Result:\n", addition_result)
print("\nSubtraction Result:\n", subtraction_result)


Matrix A:
 [[1 2 3]
 [4 5 6]]

Matrix B:
 [[-1 -2 -3]
 [-4 -5 -6]]

Addition Result:
 [[0 0 0]
 [0 0 0]]

Subtraction Result:
 [[ 2  4  6]
 [ 8 10 12]]


In [11]:
elementwise_multiply_result = np.multiply(A, B)
print("\nElement-wise Multiplication Result:\n", elementwise_multiply_result)


Element-wise Multiplication Result:
 [[ -1  -4  -9]
 [-16 -25 -36]]


In [12]:
b = 2
A_plus_b = A + b
print("\nMatrix A + b:\n", A_plus_b)


Matrix A + b:
 [[3 4 5]
 [6 7 8]]


In [15]:
C = np.array([[1, 2, 3], [4, 5, 6]])
D = np.array([[1, 1], [1, 1], [1, 1]])

matrix_multiply_result = np.dot(C, D)
print("\nMatrix Multiplication Result:\n", matrix_multiply_result)


Matrix Multiplication Result:
 [[ 6  6]
 [15 15]]


In [16]:
v = np.array([1, 2, 3])
u = np.array([1, 1, 1])

norm_v = np.linalg.norm(v)
norm_u = np.linalg.norm(u)

print("\nEuclidean of v:", norm_v)
print("Euclidean of u:", norm_u)



Euclidean Norm of v: 3.7416573867739413
Euclidean Norm of u: 1.7320508075688772


In [17]:
vector_11 = np.array([11, 22, 33, 44, 55])
elements_from_second_to_last = vector_11[-2:]
print("\nElements from second-to-last to the end:", elements_from_second_to_last)


Elements from second-to-last to the end: [44 55]
